# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: build
      run: docker build -t image-name:latest .
    
    - name: login
      run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    
    - name: tag
      run: docker tag image-name:latest ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:SNAPSHOT-${{ github.run_number }}
    
    - name: push
      run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:SNAPSHOT-${{ github.run_number }}

  cd-image-update:
    needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: clone
      run: git clone https://github.com/wahaoo-dev/dev-test-cd.git && cd dev-test-cd && pwd && ls
    - name: config
      run: git config --global user.name action && git config --global user.email action@github.com
    #- name: set remote url
    #  run: git remote set-url origin https://${GITHUB_USER}:${GITHUB_PWD}@github.com/wahaoo-dev/dev-test-cd.git
    - name: update tag
      run: sed -i "s#${{ secrets.DOCKER_REPO }}.*#${{ secrets.DOCKER_REPO }}:SNAPSHOT-${{ github.run_number }}#g" go-dev-test/deployment.yaml && git status
    - name: push
      run: git add go-dev-test/deployment.yaml && git commit -m "update tag SNAPSHOT-${{ secrets.DOCKER_REPO }}" && git push origin master
